import datetime
import sys
import streamlit as st
import requests

BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title="🛫 AI Travel Planner",
    page_icon="🛫",
    layout="centered",
    initial_sidebar_state="expanded"
)

st.title("🛫 AI Travel Planner")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("How can I help you in planning your next adventure?")

with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Submit")

if submit_button and user_input.strip():
    try:
        # Show user message
        # Show thinking spinner while processing
        with st.spinner("Bot is thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer found.")
            markdown_content = f""" AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}
            # **Created by:** Atriyo's Travel Agent

            ---

            {answer}

            ---
            "This travel plan was generated by AI. Please verify all information."
            ---
            """
            st.markdown(markdown_content)

        else:
            st.error(" Bot failed to respond: "+ response.text)

    except Exception as e:
        raise f"The response failed due to {e}"
    